[package]
name = "audio-db-query"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
anyhow = "1.0"
camino = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.15.0"
